"""create plates violations lookups tables

Revision ID: df4411e053fa
Revises: 
Create Date: 2026-09-21 19:30:41.851373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df4411e053fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('plate_type', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lookups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_id', sa.Integer(), nullable=False),
    sa.Column('queried_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plate_id'], ['plates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summons_number', sa.String(), nullable=False),
    sa.Column('plate_id', sa.Integer(), nullable=False),
    sa.Column('amount_due', sa.Numeric(), nullable=True),
    sa.Column('total_amount', sa.Numeric(), nullable=True),
    sa.Column('violation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['plate_id'], ['plates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('summons_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('violations')
    op.drop_table('lookups')
    op.drop_table('plates')
    # ### end Alembic commands ###
